Added Redis support for BedWars1058 Bungee mode
andrei1058/BedWars1058 pull request #12
Opened 2021-11-01 11:37 UTC by iiProCraft

Implemented redis support with BedWars1058 so if you want to use redis instead of sockets just enable redis at config.yml

2021-11-01 11:42 UTC, ken0k commented
It's good to be supported by redis, it's better than sockets.

2021-11-01 11:50 UTC, andrei1058 commented
We need this implementation as well on BedWarsProxy so we can test it before production.

2021-11-01 11:52 UTC, iiProCraft commented
> We need this implementation as well on BedWarsProxy so we can test it before production.

Yes i am working on it.

2021-12-19 16:04 UTC, andrei1058 requested changes

2021-12-19 16:04 UTC, andrei1058 commented on bedwars-plugin/pom.xml
> +            <scope>compile</scope>
this should not be compiled

2021-12-19 16:04 UTC, andrei1058 commented on bedwars-plugin/src/main/java/com/andrei1058/bedwars/lobbysocket/LoadedUsersCleaner.java
> +                if (op.getName() != null) {
op can be null

2021-12-19 16:05 UTC, andrei1058 commented
We need this on BWP as well before posting the update.

2021-12-19 18:39 UTC, ajgeiss0702 commented on bedwars-plugin/src/main/java/com/andrei1058/bedwars/lobbysocket/LoadedUsersCleaner.java
> +                if (op.getName() != null) {
It cannot. According to the javadocs:

> This will return an object even if the player does not exist. To this method, all players will exist.

2022-03-10 21:45 UTC, iiProCraft commented
Moved to https://github.com/andrei1058/BedWars1058/pull/441

2022-03-10 21:45 UTC, iiProCraft commented
Moved to https://github.com/andrei1058/BedWars1058/pull/441

2022-03-10 21:45 UTC, closed without merging