Modify the amount to diamond and emerald generators
andrei1058/BedWars1058 pull request #144
Opened 2021-11-30 07:22 UTC by reussy

I remove the check **isFirstTime** because it never overwrites existing values, so when creating the file or checking that the new paths are missing it will always add them without affecting the others
The new paths are created by default with 1

Closes #136

2021-12-01 19:48 UTC, ajgeiss0702 requested changes

2021-12-01 19:48 UTC, ajgeiss0702 commented on bedwars-plugin/src/main/java/com/andrei1058/bedwars/configuration/GeneratorsConfig.java
> +        //if (isFirstTime()) {
If you are going to remove this, please actually remove it, then fix the indenting for the lines below.

2021-12-01 22:09 UTC, ajgeiss0702 approved these changes
Looks good

2021-12-01 23:12 UTC, andrei1058 commented
I'm worrying the thing you removed was there for a reason, but I can't check it right now because reviewing on mobile is not the greatest :(

2021-12-02 00:10 UTC, reussy commented
I have checked that everything was OK before committing
Checking the code only verifies if it is the first time you start the plugin (that the files do not exist) but it does not do much more than that

2021-12-02 00:21 UTC, ajgeiss0702 commented
I just double-checked, it looks like the isFirstTime method is unnecessary. The method was not used for the main config, and we know the main config works fine.

2021-12-03 20:14 UTC, andrei1058 approved these changes

2021-12-03 20:14 UTC, merged

2021-12-03 20:15 UTC, andrei1058 commented
Thank you very much!