Clear arrows from player's body on death (FIXED)
andrei1058/BedWars1058 pull request #151
Opened 2021-11-30 21:41 UTC by CoachYT1

2021-12-01 20:29 UTC, andrei1058 commented
Did you even import CraftPlayer? I don't think this will work with all version...

2021-12-01 20:42 UTC, ajgeiss0702 commented
It looks like CraftPlayer was already imported from other things. It compiles (as you can see in the checks).

I would also like to see that it works on all versions.

2021-12-03 20:36 UTC, andrei1058 commented
can someone test this on 1.12 and 1.13 or newer?

2021-12-16 10:57 UTC, CoachYT1 commented
Tested with 1.8.8, 1.9.4, 1.12.2, 1.15.2, 1.16.5

2021-12-17 22:08 UTC, andrei1058 requested changes
please align with master. 1.18 support has been added

2021-12-17 22:08 UTC, andrei1058 commented on versionsupport_1_16_R1/src/main/java/com/andrei1058/bedwars/support/version/v1_16_R1/v1_16_R1.java
> +        System.out.println("1.16_R1");
Remove this

2021-12-17 23:24 UTC, CoachYT1 commented on versionsupport_1_16_R1/src/main/java/com/andrei1058/bedwars/support/version/v1_16_R1/v1_16_R1.java
> +        System.out.println("1.16_R1");
Done

2021-12-18 17:41 UTC, andrei1058 approved these changes

2021-12-19 15:50 UTC, merged