PAPI support to items
andrei1058/BedWars1058 pull request #155
Opened 2021-12-01 17:17 UTC by reussy

added support for PAPI in lobby, pre-game and spectator items (item name and item lore)
added replace method for string list in SupportPAPI

Closes #154

2021-12-01 19:34 UTC, ajgeiss0702 requested changes

2021-12-01 19:34 UTC, ajgeiss0702 commented on bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/Arena.java
> +                        //getMsg(p, Messages.GENERAL_CONFIGURATION_LOBBY_ITEMS_NAME.replace("%path%", item)),
These added comments seem unnecessary and you should probably remove them. Other than that, looks good to me. (also dont forget the same comments are in other places in your pr)

2021-12-03 05:17 UTC, ajgeiss0702 approved these changes

2021-12-03 20:29 UTC, andrei1058 commented
Is it ok to use papi async?

2021-12-05 09:59 UTC, reussy commented
> Is it ok to use papi async?

I have never tried it and I don't think it's necessary either

2021-12-05 20:47 UTC, ajgeiss0702 commented
> Is it ok to use papi async?

Unless the placeholder does something specific to minecraft that requires it to by sync (which afaik none do) it should be fine

2021-12-12 00:14 UTC, andrei1058 commented
> > Is it ok to use papi async?
> 
> I have never tried it and I don't think it's necessary either

They are used async in your context :)

2021-12-12 00:16 UTC, ajgeiss0702 commented
I’d also like to note that I parse placeholders async in ajLeaderboards and have never had any issues with that

2021-12-19 16:00 UTC, merged