Ender Pearl sound
andrei1058/BedWars1058 pull request #169
Opened 2021-12-05 07:55 UTC by reussy

Implements a sound for arena players when the ender pearl is hit on a block.

Closes #159

2021-12-19 15:55 UTC, andrei1058 requested changes

2021-12-19 15:55 UTC, andrei1058 commented on bedwars-plugin/src/main/java/com/andrei1058/bedwars/listeners/EnderPearlLanded.java
> +        Sound sound = Sound.valueOf(Sounds.getSounds().getYml().getString("ender-pearl-landed.sound"));
Just use Sounds.playSound("ender-pearl-landed", iArena.getPlayers())

2021-12-19 15:55 UTC, andrei1058 commented
also align with master

2022-02-02 18:41 UTC, andrei1058 commented
bump

2022-02-05 07:50 UTC, reussy commented
> bump

Due problems with my PC I made a new pr
#355

2022-02-05 07:50 UTC, closed without merging