Decimals in generator delay value
andrei1058/BedWars1058 pull request #252
Opened 2022-01-05 06:43 UTC by reussy

Allows using decimals in the generator delay.
For avoid visual bugs I used Math#round in {seconds} placeholder.

Closes #247

2022-01-05 18:34 UTC, ajgeiss0702 commented on bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/OreGenerator.java
> +                    delay =  getGeneratorsCfg().getInt(getGeneratorsCfg().getYml().get(arena.getGroup() + "." + ConfigPath.GENERATOR_DIAMOND_TIER_II_DELAY) == null ?
was this accidental?

2022-01-05 18:37 UTC, ajgeiss0702 requested changes
From what I can see this will just round the delay, but wont actually use the decimal value

2022-01-05 18:39 UTC, reussy commented on bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/OreGenerator.java
> +                    delay =  getGeneratorsCfg().getInt(getGeneratorsCfg().getYml().get(arena.getGroup() + "." + ConfigPath.GENERATOR_DIAMOND_TIER_II_DELAY) == null ?
yes, but idk why it was sent this way

2022-01-05 18:40 UTC, reussy commented on bedwars-plugin/src/main/java/com/andrei1058/bedwars/arena/OreGenerator.java
> +                    delay =  getGeneratorsCfg().getInt(getGeneratorsCfg().getYml().get(arena.getGroup() + "." + ConfigPath.GENERATOR_DIAMOND_TIER_II_DELAY) == null ?
> 

yes, but idk why it was sent this way

2022-01-05 18:41 UTC, reussy commented
> From what I can see this will just round the delay, but wont actually use the decimal value
It rounds it for holograms but the value (decimal or integer) is used when spawning a new ore

2022-01-05 18:43 UTC, ajgeiss0702 commented
But from what I see you are rounding that value too

2022-01-10 19:12 UTC, andrei1058 commented
generators do not support doubles for now

2022-01-10 19:12 UTC, closed without merging