Team Eliminated Event
andrei1058/BedWars1058 pull request #449
Opened 2022-03-21 23:29 UTC by JT122406

Made a event that fires when a team has been completely eliminated

2022-03-23 21:42 UTC, andrei1058 commented
I noticed PrePartyListener was deleted. Any notes about that?

2022-03-23 21:54 UTC, JT122406 commented
> I noticed PrePartyListener was deleted. Any notes about that?

Nope just it was deprecated and I messed around with removing it and nothing broke but I didn't mean to push it to my branch that's my bad

2022-03-27 20:38 UTC, andrei1058 requested changes

2022-03-27 20:38 UTC, andrei1058 commented on bedwars-plugin/src/main/java/com/andrei1058/bedwars/BedWars.java
> +                registerEvents(new ServerPingListener(), new PrePartyListener(), new JoinListenerBungeeLegacy());
you registered back pre party in a wrong position. move it up in the if autoscale

2022-03-27 21:20 UTC, closed without merging