Added Minimal Bangla Language
andrei1058/BedWars1058 pull request #50
Opened 2021-11-05 10:54 UTC by Itsmemonzu

**This language file used both Bangla and English to make it understandable. Hope this helps!**

2021-11-05 19:47 UTC, andrei1058 commented
I'll be waiting for a complete translation, otherwise you can close this yourself. We do not need partial implementations.

2021-11-06 03:03 UTC, Itsmemonzu commented
Okay, I'll make sure to translate it to full Bangla today!

2021-11-06 03:06 UTC, Itsmemonzu commented
Okay, I'll make sure to translate it fully today!

2021-11-06 14:04 UTC, andrei1058 commented on bedwars-plugin/src/main/java/com/andrei1058/bedwars/language/Bangla.java
> +        yml.addDefault(Messages.SHOP_NEW_PURCHASE, "{prefix}&a&aApni &6{item} &akinlen.");
fix tis color code please

2021-11-06 14:06 UTC, andrei1058 requested changes

2021-11-06 14:06 UTC, andrei1058 commented on bedwars-plugin/src/main/java/com/andrei1058/bedwars/language/Bangla.java
> +        yml.addDefault(Messages.FORMATTING_ACTION_BAR_TRACKING, "&fTracking: {team} &f- duratto: {distance}m");
Please use upper case for duratto

2021-11-06 14:15 UTC, merged