Fix #508
andrei1058/BedWars1058 pull request #509
Opened 2022-05-07 15:19 UTC by hugeBlack

The onEnabled(a) call is somehow in the catch block, which can be hardly reached. So it is moved to be invoked after slime.generateWorld(finalWorld)

2022-05-11 11:10 UTC, hugeBlack commented
I also added simplified Chinese translation.

2022-05-17 05:30 UTC, hugeBlack commented
It seems that the getPlayerHead method is actually working properly in 1.18.

2022-05-17 07:53 UTC, hugeBlack commented
Correctly set tnt igniter and add all stained glass to TNT whitelist for version 1.18_R1

2022-05-17 09:47 UTC, hugeBlack commented
fix for #522 
Potion listener registration is somehow placed in the switch block for deprecated, so that the listener is only registered in these deprecated version

2022-05-18 16:33 UTC, hugeBlack commented
The reason why noSuchMethod is thrown when isInvisibilityPotion method is called is that the isInvisibilityPotion method somehow vanished from VersionSupport and all version support classes in version 22.3.4.

2022-08-25 20:16 UTC, andrei1058 requested changes

2022-08-25 20:16 UTC, andrei1058 commented on bedwars-plugin/src/main/java/com/andrei1058/bedwars/listeners/InvisibilityPotionListener.java
> +            Method testPotionMethod = vs.getDeclaredMethod("isInvisibilityPotion",org.bukkit.inventory.ItemStack.class);
why is reflection being used here?

2022-08-25 20:16 UTC, andrei1058 commented on resetadapter_slime/src/main/java/com/andrei1058/bedwars/arena/mapreset/slime/SlimeAdapter.java
> +                    onEnable(a);
this is wrong. why you making it recursive in here?

2022-08-25 20:16 UTC, andrei1058 commented
please resolve conflicts

2022-12-20 17:52 UTC, closed without merging