Prevent player from shouting in solo arenas
andrei1058/BedWars1058 pull request #707
Opened 2023-03-09 06:12 UTC by porudev

I think it's unnecessary for player to be able to shout in Solo. So i added the check to the shout command

2023-03-09 06:14 UTC, porudev commented
I have OCD :(

2023-03-09 21:29 UTC, tomkeuper commented
I dont think its good to remove the permission of shouting when there is just one in the team. 

If a player tries to talk to others by using the shout command it will fail and making then think its not possible. But thats not the case.

2023-03-10 05:28 UTC, porudev commented
> I dont think its good to remove the permission of shouting when there is just one in the team.
> 
> If a player tries to talk to others by using the shout command it will fail and making then think its not possible. But thats not the case.

i think i should add a message config for that, also the check isn't for single person in team. It check max amount of team member is set for that arena so 1 should be Solo. Let's just mark this as WIP

2023-03-10 06:14 UTC, porudev commented
I also fixed a typo

2023-03-10 07:10 UTC, porudev commented on bedwars-api/src/main/java/com/andrei1058/bedwars/api/configuration/ConfigPath.java
> +    public static final String GENERAL_CONFIGURATION_ALLOWED_COMMANDS = "allowed-commands";
There was a typo here called Ceneral instead of General

2023-03-13 19:01 UTC, tomkeuper requested changes

2023-03-13 19:01 UTC, tomkeuper commented on bedwars-plugin/src/main/java/com/andrei1058/bedwars/BedWars.java
> +        new Vietnam();
Oopsie?

2023-03-13 19:06 UTC, tomkeuper commented
can you explain what this does exactly?
Does it disable shouting when in a solo gamemode? Will this completely stop players from talking to each other? 

Maybe the best solution would be to make all messages act like a normal message. So it wouldnt matter if you are shouting or not.  Like I mentioned before, I think its counter intuitive to block players from shouting completely.

2023-03-13 21:00 UTC, porudev commented
> can you explain what this does exactly? Does it disable shouting when in a solo gamemode? Will this completely stop players from talking to each other?
> 
> Maybe the best solution would be to make all messages act like a normal message. So it wouldnt matter if you are shouting or not. Like I mentioned before, I think its counter intuitive to block players from shouting completely.

This should add a config where you can disable player's ability to use shout in solos arena (1 max in team). It will be disabled by default so no worries on it making change to the plugin. Only people who use it really matter. Thank you, and also the vietnamese language isn't ready yet since im still working on it. But the solo shout prevention option should work perfectly now

2023-03-13 21:03 UTC, closed without merging