Fix 1.16.5 support
andrei1058/BedWars1058 pull request #962
Opened 2024-01-24 04:32 UTC by ImYenil

Fixed bug where version 1.16.5 was not supported

2024-02-03 16:20 UTC, andrei1058 commented on bedwars-plugin/pom.xml
> +            <version>23.12.1-SNAPSHOT</version>
remove snapshot from here please

2024-02-03 16:20 UTC, andrei1058 requested changes
let me know when you removed the snapshot from the version string

2024-02-03 16:28 UTC, andrei1058 commented
New version for sidebar lib: **24.1**

2024-02-07 06:27 UTC, ImYenil commented
> let me know when you removed the snapshot from the version string

done

2025-02-10 17:01 UTC, andrei1058 commented
I am going to close this since it looks fixed on maste.r

2025-02-10 17:01 UTC, closed without merging